# Generated by Django 4.1.1 on 2022-09-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_department_alter_employee_options_employee_unique_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['ename', 'eemail'], name='employee_ename_361546_idx'),
        ),
    ]
