# Generated by Django 4.1.1 on 2022-09-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_new_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='new_slug',
        ),
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
