# Generated by Django 4.1.1 on 2022-09-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
